# Lab Two: Data Cleaning

Data cleaning is the very first part of any data analysis and/or machine learning project. In this lab, you will be going over some of the common data issues and applying suitable fixes.

##### Loading libraries needed and the data

In [1]:
import pandas as pd
import numpy as np

### Explaining the data we will be using for this and the next few labs

In this example, we have 2 datasets. The datasets from two different hypothetical clinics, "Clinic1" and "Clinic2" which diagnose patients with a novel device that takes many measurements. The final goal is to see if they have a particular disease or not.

Measurements taken from patients in the two clinics are presented in dataframes `Lab2_df1.csv` and we also have an inspection log, recorded in `Lab2_df2.csv` file for the devices used in "Clinic1" and "Clinic2" where many variables from the device are measured.

Two of these variables, `'M1'` and `'M3'`, are believed to affect the readings taken from the patients. The `Lab2_df1` dataset is labelled with an actual diagnosis of whether the patient had the disease or not, and the goal is to predict the existence of the disease based on the measurements taken from the patients. Since the variables of the devices, measured in inspection, affects the measurements taken from patients in clinics, they should also be considered. Here are the data frames:

#### Note: Cells which have '[A]' represents the activity you have to do.

In [2]:
# loading the 'Lab2_df1.csv' csv data
df1 = pd.read_csv('Lab2_df1.csv')

# This makes it so we are able to see 100 rows when displaying the data
pd.set_option('display.max_rows', 100)

In [3]:
# displaying the first five entries of the dataframe

df1.head()

,Unnamed: 0,Examination Date,Name,Gender,Age,Mode,H,H1,M,DD,Diagnosis
0,0,6/10/2011,Cody Watson,male,72,d,_,_,5.058993,1.481877,No
1,1,2/20/2011,Jonathan Duke,male,9,e,104.0876332,105.0876332,6.531724,2.266884,No
2,2,6/27/2011,Charlene Houseworth,female,59,f,102.9043152,103.9043152,6.273313,0.396333,Yes
3,3,9/22/2010,Gregory Curci,Male,23,g,152.6516553,153.6516553,7.333626,0.557534,Yes
4,4,6/10/2011,Cody Watson,male,72,d,_,_,5.058993,1.481877,No

In [4]:
df1.shape

(61, 11)

## Looking at issues with the data

##### Unique values of the `'Gender'` feature.

In [5]:
# checking unique entries in the 'Gender' column

df1['Gender'].unique()

array(['male', 'female', 'Male', 'fmeale'], dtype=object)

##### Unique values of the `'Mode'` feature.

In [6]:
# checking unique entries in the 'Mode' column

df1['Mode'].unique()

array(['d', 'e', 'f', 'g', '_', 'F', 'h', 'a'], dtype=object)

##### Observing the data types of each column.

In [7]:
# checking data types of all columns in the dataframe

df1.dtypes

Unnamed: 0            int64
Examination Date     object
Name                 object
Gender               object
Age                   int64
Mode                 object
H                    object
H1                   object
M                   float64
DD                  float64
Diagnosis            object
dtype: object

# Lab Activity One: Guided Data Cleaning

##### It is generally a good idea to make a copy of the master dataset for cleaning so you can always go back if ever needed.

In [8]:
# making a copy of the data frame

df_clean = df1.copy()

##### [A] Drop the `'Unnamed: 0'` column

In [9]:
# removing unwanted 'Unnamed' column
df_clean = df_clean.drop(columns=['Unnamed: 0'])

# confirming that 'Unnamed' column is no longer in the dataframe
df_clean.head()

,Examination Date,Name,Gender,Age,Mode,H,H1,M,DD,Diagnosis
0,6/10/2011,Cody Watson,male,72,d,_,_,5.058993,1.481877,No
1,2/20/2011,Jonathan Duke,male,9,e,104.0876332,105.0876332,6.531724,2.266884,No
2,6/27/2011,Charlene Houseworth,female,59,f,102.9043152,103.9043152,6.273313,0.396333,Yes
3,9/22/2010,Gregory Curci,Male,23,g,152.6516553,153.6516553,7.333626,0.557534,Yes
4,6/10/2011,Cody Watson,male,72,d,_,_,5.058993,1.481877,No

In [10]:
# confirming the number of columns has reduced by 1 after removing 'Unnamed' column

df_clean.shape

(61, 10)

##### [A] Fix the data in the `'Gender'` column.
> Hint: make it so there are 2 unique entries, `'male'` and `'female'`.

In [11]:
# check the unique entries for 'Gender' column

df_clean['Gender'].unique()

array(['male', 'female', 'Male', 'fmeale'], dtype=object)

In [12]:
# rename 'Male' to 'male' and 'fmeale' to 'female'

df_clean['Gender'] = df_clean['Gender'].replace('Male', 'male')
df_clean['Gender'] = df_clean['Gender'].replace('fmeale', 'female')

Check the 'Gender' column again

In [13]:
# check the unique entries for 'Gender' column after cleaning

df_clean['Gender'].unique()

# now there are 2 unique entries: 'male' and 'female'

array(['male', 'female'], dtype=object)

##### [A] Fix the data in the `'Mode'` column.
> Hint: Check for lower and upper case entries

In [14]:
# check the unique entries for 'Mode' column

df_clean['Mode'].unique()

array(['d', 'e', 'f', 'g', '_', 'F', 'h', 'a'], dtype=object)

In [15]:
# change upper case F to lower case

df_clean['Mode'].replace('F', 'f', inplace= True)

In [16]:
# check the unique entries for 'Mode' column after cleaning
df_clean['Mode'].unique()

array(['d', 'e', 'f', 'g', '_', 'h', 'a'], dtype=object)

### Setting The Correct Data Type

##### [A] Change the `'H'` column to numeric data `type(float64)` instead of `'object'`.

In [17]:
# convert data type of 'H' columnn from 'object' to 'numeric'

df_clean['H'] = pd.to_numeric(df_clean['H'], errors='coerce')

*Check* the 'H' column again

In [18]:
df_clean['H'].dtypes

dtype('float64')

##### [A] Convert `'Examination date'` column to `datetime` type.

In [19]:
# convert data type of 'Examination Date' columnn is in 'datetime'

df_clean['Examination Date'] = pd.to_datetime(df_clean['Examination Date'])

In [20]:
# confirming that the data types for columns 'H' and 'Examination Date' has changed to 'float64' and 'datetime' respectively

df_clean.dtypes

Examination Date    datetime64[ns]
Name                        object
Gender                      object
Age                          int64
Mode                        object
H                          float64
H1                          object
M                          float64
DD                         float64
Diagnosis                   object
dtype: object

##### Using the `gender_type` key we set the `'Gender'` column as categorical data.

In [21]:
gender_type = pd.CategoricalDtype(categories=["female", "male"])

df_clean["Gender"] = df_clean["Gender"].astype(gender_type)

In [22]:
# checking that Gender column data type is now category

df_clean["Gender"].dtypes

CategoricalDtype(categories=['female', 'male'], ordered=False, categories_dtype=object)

##### [A] Replicate how we changed the gender column to categorical but this time for the `'Mode'` column.

In [23]:
# Convert 'Mode' column to categorical using the defined mode_type

mode_type = pd.CategoricalDtype(categories=['d', 'e', 'f', 'g', '_', 'h', 'a'])
df_clean["Mode"] = df_clean["Mode"].astype(mode_type)

In [24]:
# checking that the data type for 'Mode' column has changed from object to category
df_clean["Mode"].dtypes

CategoricalDtype(categories=['d', 'e', 'f', 'g', '_', 'h', 'a'], ordered=False, categories_dtype=object)

##### [A] Again, change the `'Diagnosis'` column to categorical replicating above the example above.

In [25]:
# making a list of unique entries for 'Diagnosis' column

df_clean['Diagnosis'].unique()

array(['No', 'Yes', '_'], dtype=object)

In [26]:
# Convert 'Diagnosis' column to categorical using the defined diagnosis_type

diagnosis_type = pd.CategoricalDtype(categories=['No', 'Yes', '_'])
df_clean["Diagnosis"] = df_clean["Diagnosis"].astype(diagnosis_type)

In [27]:
# checking that the data type for 'Diagnosis' column has changed from object to category

df_clean["Diagnosis"].dtypes

CategoricalDtype(categories=['No', 'Yes', '_'], ordered=False, categories_dtype=object)

In [28]:
# checking that the data type for all column to confirm all dtype changes made to Examination Date, Gender,, Mode, H, and Diagnosis columns are effected

df_clean.dtypes

Examination Date    datetime64[ns]
Name                        object
Gender                    category
Age                          int64
Mode                      category
H                          float64
H1                          object
M                          float64
DD                         float64
Diagnosis                 category
dtype: object

### Duplicate Entries
- Duplicate entities in a dataset is not good to have as it  can use overfit and is redundant information

##### [A] Check for duplicate entries and delete them

In [29]:
duplicate_rows = df_clean.duplicated()

In [30]:
display(duplicate_rows)

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33    False
34    False
35    False
36     True
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
60    False
dtype: bool

before using tilde operator
True = Duplicated, False = not duplicated

After using tilde operator:
False = Duplicated, Trues = Not _ duplicated

In [31]:
# removing duplicates from dataset

df_clean = df_clean[~duplicate_rows]

In [32]:
# displaying data rows that are unique after removing duplicates

df_clean

,Examination Date,Name,Gender,Age,Mode,H,H1,M,DD,Diagnosis
0,2011-06-10,Cody Watson,male,72,d,NaN,_,5.058993,1.481877,No
1,2011-02-20,Jonathan Duke,male,9,e,104.087633,105.0876332,6.531724,2.266884,No
2,2011-06-27,Charlene Houseworth,female,59,f,102.904315,103.9043152,6.273313,0.396333,Yes
3,2010-09-22,Gregory Curci,male,23,g,152.651655,153.6516553,7.333626,0.557534,Yes
5,2011-07-21,Linda Sawicki,female,17,g,67.239054,68.23905431,3.642516,3.765706,Yes
6,2011-05-06,Ruth Morgan,female,19,_,54.050309,55.0503086,7.193318,-0.173915,_
7,2011-07-05,Shane Acosta,male,5,f,47.046446,48.04644557,4.808863,6.446874,No
8,2010-10-31,Tania Fuoco,female,41,f,NaN,_,7.637614,-0.655884,No
9,2011-05-01,Arla Czachorowski,female,36,f,109.645724,110.6457241,7.006120,2.405082,No
10,2010-08-22,Sheila Thomas,female,41,_,108.272150,109.2721498,7.369781,9.350549,_
11,2011-01-24,Jimmy Martinez,male,36,e,106.403539,107.4035386,4.329964,-2.105617,Yes
12,2011-02-04,Phillip Boyd,male,2,f,116.181745,117.1817452,7.817222,5.456586,No
13,2010-09-01,John Lesser,male,76,f,NaN,_,4.193204,-1.491731,_
14,2011-06-16,David Montgomery,male,4,f,146.325322,147.3253216,4.370916,-5.119345,Yes
15,2011-06-19,Anita Mcgrew,female,32,e,63.210088,64.21008797,5.253893,5.946163,No
16,2010-12-03,Daniel Moore,male,10,e,116.219153,117.2191531,6.446360,2.041393,No
17,2011-04-11,Holly Molina,female,43,d,NaN,_,5.088270,4.504290,Yes
18,2011-04-26,Heather Esquivel,female,15,_,33.128323,34.12832279,6.461212,0.213089,No
19,2011-02-01,Frankie Mitchener,male,43,f,131.127339,132.127339,4.855666,2.858591,Yes
20,2010-10-22,Cecilia Allen,female,33,e,146.680638,147.6806376,5.767645,1.362450,Yes
21,2011-01-27,James Bush,male,40,f,76.439902,77.43990201,6.853351,7.144657,No
22,2010-12-21,Mark Yoder,male,44,g,92.054403,93.05440312,5.823945,3.069055,Yes
23,2010-09-03,Marguerite Janis,female,1,f,124.294828,125.294828,6.188929,-4.614200,Yes
24,2011-06-11,Bennie Esker,male,59,e,106.719698,107.7196982,6.085462,-8.263394,_
25,2010-11-08,Jamal Mccullough,male,37,f,129.736820,130.7368202,5.858931,2.689617,No
26,2011-05-31,Linda Hathaway,female,36,e,86.446664,87.44666438,5.025699,-1.713491,Yes
27,2011-06-14,Kiera Phan,female,18,e,119.601777,120.601777,5.966730,3.440177,No
28,2011-03-20,Katherine Collelo,female,47,_,123.201676,124.201676,4.843007,5.064505,Yes
29,2010-09-30,David Wuertz,male,83,g,NaN,_,6.725675,-1.294398,No
30,2011-08-14,Jaclyn Mcauley,female,81,e,NaN,_,3.702969,-1.740168,Yes
31,2011-04-28,Ramona Crow,female,592,f,91.659868,92.65986797,6.397731,4.106246,No
33,2011-04-11,John Castro,male,56,f,NaN,_,5.507379,-2.492783,No
34,2011-02-06,Adele Crutchfield,female,10,e,112.728028,113.7280281,4.797970,2.266737,Yes
35,2011-07-01,Bud Ross,male,27,f,72.415300,73.41530029,6.214333,2.746591,No
37,2011-01-09,Ruthie Lairy,female,15,h,116.144212,117.144212,3.897702,-0.877424,Yes
38,2010-12-15,Daryl Webb,male,34,e,110.581368,111.5813683,5.949869,2.007187,Yes
39,2011-07-27,Heidi Moss,female,18,d,96.770824,97.77082449,5.066335,3.500904,No
40,2011-06-07,James Kramer,male,29,f,92.186883,93.18688263,4.192012,-2.593210,No
41,2010-12-23,Ernest Oley,male,42,g,NaN,_,6.686434,4.710838,No
42,2010-10-05,Jennifer Wagner,female,38,g,119.876747,120.8767474,5.720786,-2.959588,Yes
43,2011-05-27,Todd Renwick,male,24,e,112.919674,113.9196741,6.369615,-2.065630,No
44,2011-05-13,Enrique Traino,male,53,f,69.870661,70.87066139,5.600482,-2.195055,Yes
45,2010-10-24,Jeannette Augenstein,female,25,e,84.674508,85.67450841,4.947849,-7.013755,Yes
46,2011-04-19,William Henderson,male,31,f,71.967347,72.96734654,6.730994,-1.491034,Yes
47,2010-09-07,Virginia Howe,female,31,f,92.903873,93.90387335,5.513919,4.808042,No
48,2010-12-15,Theodore Wells,male,47,d,85.911229,86.91122925,5.280809,-2.505498,Yes
49,2010-11-12,Stephen Jones,male,48,f,129.145707,130.1457066,5.557521,-1.655331,No
50,2010-09-30,Maribel House,female,12,e,118.837180,119.8371796,5.501253,4.932782,Yes
51,2011-04-08,Tosha Mcnelis,female,72,f,120.960522,121.960522,5.554830,3.303376,No
52,2011-06-30,William Knuth,male,31,a,149.971966,150.9719662,4.714037,-2.236160,Yes
53,2010-10-05,Lori Reynolds,female,54,f,NaN,_,5.483929,1.528417,No
54,2011-04-25,Minerva Wilbur,female,13,_,101.717648,102.7176477,6.376439,-1.193141,No
55,2011-06-26,Stacy Gray,male,15,e,104.192933,105.1929329,5.759295,4.203775,Yes
56,2011-08-04,Sherry Dafonte,female,42,e,109.866307,110.8663068,4.137636,6.405663,No
57,2011-08-14,Melvin Yono,male,37,e,100.379104,101.3791042,6.295158,-2.297059,Yes
58,2011-04-19,Robert Young,male,77,f,NaN,_,5.524661,3.867672,No
59,2011-05-29,Gerald Salem,male,35,e,98.547989,99.54798923,2.688670,1.897595,Yes
60,2011-05-15,Joseph Beatty,male,33,f,120.669018,121.6690182,5.241279,1.911511,No

In [33]:
# checking the shape of the dataframe after removing duplicates

df_clean.shape

(58, 10)

##### [A] Once you delete a row in your dataset the index of that row is also deleted. Reset the index of the dataset so it in proper order.
> Hint: use the `dataframe.reset_index` function and set the drop parameter to `True`.

In [34]:
#reseting column index after removing duplicates

df_clean.reset_index(drop = True)

,Examination Date,Name,Gender,Age,Mode,H,H1,M,DD,Diagnosis
0,2011-06-10,Cody Watson,male,72,d,NaN,_,5.058993,1.481877,No
1,2011-02-20,Jonathan Duke,male,9,e,104.087633,105.0876332,6.531724,2.266884,No
2,2011-06-27,Charlene Houseworth,female,59,f,102.904315,103.9043152,6.273313,0.396333,Yes
3,2010-09-22,Gregory Curci,male,23,g,152.651655,153.6516553,7.333626,0.557534,Yes
4,2011-07-21,Linda Sawicki,female,17,g,67.239054,68.23905431,3.642516,3.765706,Yes
5,2011-05-06,Ruth Morgan,female,19,_,54.050309,55.0503086,7.193318,-0.173915,_
6,2011-07-05,Shane Acosta,male,5,f,47.046446,48.04644557,4.808863,6.446874,No
7,2010-10-31,Tania Fuoco,female,41,f,NaN,_,7.637614,-0.655884,No
8,2011-05-01,Arla Czachorowski,female,36,f,109.645724,110.6457241,7.006120,2.405082,No
9,2010-08-22,Sheila Thomas,female,41,_,108.272150,109.2721498,7.369781,9.350549,_
10,2011-01-24,Jimmy Martinez,male,36,e,106.403539,107.4035386,4.329964,-2.105617,Yes
11,2011-02-04,Phillip Boyd,male,2,f,116.181745,117.1817452,7.817222,5.456586,No
12,2010-09-01,John Lesser,male,76,f,NaN,_,4.193204,-1.491731,_
13,2011-06-16,David Montgomery,male,4,f,146.325322,147.3253216,4.370916,-5.119345,Yes
14,2011-06-19,Anita Mcgrew,female,32,e,63.210088,64.21008797,5.253893,5.946163,No
15,2010-12-03,Daniel Moore,male,10,e,116.219153,117.2191531,6.446360,2.041393,No
16,2011-04-11,Holly Molina,female,43,d,NaN,_,5.088270,4.504290,Yes
17,2011-04-26,Heather Esquivel,female,15,_,33.128323,34.12832279,6.461212,0.213089,No
18,2011-02-01,Frankie Mitchener,male,43,f,131.127339,132.127339,4.855666,2.858591,Yes
19,2010-10-22,Cecilia Allen,female,33,e,146.680638,147.6806376,5.767645,1.362450,Yes
20,2011-01-27,James Bush,male,40,f,76.439902,77.43990201,6.853351,7.144657,No
21,2010-12-21,Mark Yoder,male,44,g,92.054403,93.05440312,5.823945,3.069055,Yes
22,2010-09-03,Marguerite Janis,female,1,f,124.294828,125.294828,6.188929,-4.614200,Yes
23,2011-06-11,Bennie Esker,male,59,e,106.719698,107.7196982,6.085462,-8.263394,_
24,2010-11-08,Jamal Mccullough,male,37,f,129.736820,130.7368202,5.858931,2.689617,No
25,2011-05-31,Linda Hathaway,female,36,e,86.446664,87.44666438,5.025699,-1.713491,Yes
26,2011-06-14,Kiera Phan,female,18,e,119.601777,120.601777,5.966730,3.440177,No
27,2011-03-20,Katherine Collelo,female,47,_,123.201676,124.201676,4.843007,5.064505,Yes
28,2010-09-30,David Wuertz,male,83,g,NaN,_,6.725675,-1.294398,No
29,2011-08-14,Jaclyn Mcauley,female,81,e,NaN,_,3.702969,-1.740168,Yes
30,2011-04-28,Ramona Crow,female,592,f,91.659868,92.65986797,6.397731,4.106246,No
31,2011-04-11,John Castro,male,56,f,NaN,_,5.507379,-2.492783,No
32,2011-02-06,Adele Crutchfield,female,10,e,112.728028,113.7280281,4.797970,2.266737,Yes
33,2011-07-01,Bud Ross,male,27,f,72.415300,73.41530029,6.214333,2.746591,No
34,2011-01-09,Ruthie Lairy,female,15,h,116.144212,117.144212,3.897702,-0.877424,Yes
35,2010-12-15,Daryl Webb,male,34,e,110.581368,111.5813683,5.949869,2.007187,Yes
36,2011-07-27,Heidi Moss,female,18,d,96.770824,97.77082449,5.066335,3.500904,No
37,2011-06-07,James Kramer,male,29,f,92.186883,93.18688263,4.192012,-2.593210,No
38,2010-12-23,Ernest Oley,male,42,g,NaN,_,6.686434,4.710838,No
39,2010-10-05,Jennifer Wagner,female,38,g,119.876747,120.8767474,5.720786,-2.959588,Yes
40,2011-05-27,Todd Renwick,male,24,e,112.919674,113.9196741,6.369615,-2.065630,No
41,2011-05-13,Enrique Traino,male,53,f,69.870661,70.87066139,5.600482,-2.195055,Yes
42,2010-10-24,Jeannette Augenstein,female,25,e,84.674508,85.67450841,4.947849,-7.013755,Yes
43,2011-04-19,William Henderson,male,31,f,71.967347,72.96734654,6.730994,-1.491034,Yes
44,2010-09-07,Virginia Howe,female,31,f,92.903873,93.90387335,5.513919,4.808042,No
45,2010-12-15,Theodore Wells,male,47,d,85.911229,86.91122925,5.280809,-2.505498,Yes
46,2010-11-12,Stephen Jones,male,48,f,129.145707,130.1457066,5.557521,-1.655331,No
47,2010-09-30,Maribel House,female,12,e,118.837180,119.8371796,5.501253,4.932782,Yes
48,2011-04-08,Tosha Mcnelis,female,72,f,120.960522,121.960522,5.554830,3.303376,No
49,2011-06-30,William Knuth,male,31,a,149.971966,150.9719662,4.714037,-2.236160,Yes
50,2010-10-05,Lori Reynolds,female,54,f,NaN,_,5.483929,1.528417,No
51,2011-04-25,Minerva Wilbur,female,13,_,101.717648,102.7176477,6.376439,-1.193141,No
52,2011-06-26,Stacy Gray,male,15,e,104.192933,105.1929329,5.759295,4.203775,Yes
53,2011-08-04,Sherry Dafonte,female,42,e,109.866307,110.8663068,4.137636,6.405663,No
54,2011-08-14,Melvin Yono,male,37,e,100.379104,101.3791042,6.295158,-2.297059,Yes
55,2011-04-19,Robert Young,male,77,f,NaN,_,5.524661,3.867672,No
56,2011-05-29,Gerald Salem,male,35,e,98.547989,99.54798923,2.688670,1.897595,Yes
57,2011-05-15,Joseph Beatty,male,33,f,120.669018,121.6690182,5.241279,1.911511,No

##### [A] Check the data types of your dataframe and print the shape of the dataframe.

In [35]:
# checking data type for all columns in the data frame

df_clean.dtypes

Examination Date    datetime64[ns]
Name                        object
Gender                    category
Age                          int64
Mode                      category
H                          float64
H1                          object
M                          float64
DD                         float64
Diagnosis                 category
dtype: object

In [36]:
# checking number of rows and columns in the data frame

df_clean.shape

(58, 10)

# Lab Activity Two: Clean a Dataset Yourself

In this activity, you will need to clean the dataset yourself using the examples from the activity above. The `Lab2_df2.csv` is loaded and displayed for you.

In [37]:
#Read Lab2_df2.csv file

df2 = pd.read_csv('Lab2_df2.csv')
df2.head(10)

,Unnamed: 0,Inspection Date,M1,M2,M3,M4,Site Name
0,0,9/4/2010,0.079600881,0.007344,0.542921,0.000074,Clinic1
1,1,9/27/2010,_,0.000204,9.613118,0.000042,Clinic1
2,2,10/6/2010,_,0.000928,4.298943,0.000041,Clinic1
3,3,10/21/2010,0.877617221,0.002254,9.240019,0.000182,Clinic1
4,4,11/26/2010,_,0.008547,6.659528,0.000022,Clinic1
5,5,11/29/2010,0.751824622,0.006172,7.023103,0.000016,Clinic1
6,6,1/4/2011,0.9279763,0.000833,5.473454,0.000124,Clinic2
7,7,1/28/2011,0.905113763,0.008793,7.223218,0.000209,Clinic2
8,8,2/3/2011,0.091880053,0.001529,2.745545,0.000024,Clinic1
9,9,2/4/2011,_,0.007507,4.472094,0.000035,Clinic2

##### [A] Figure out the issues with this dataset and apply the cleaning methods

In [38]:
# making a copy of the dataframe
df2_clean = df2.copy()

#displaying the first five rows of the dataframe copied
df2_clean.head()

,Unnamed: 0,Inspection Date,M1,M2,M3,M4,Site Name
0,0,9/4/2010,0.079600881,0.007344,0.542921,0.000074,Clinic1
1,1,9/27/2010,_,0.000204,9.613118,0.000042,Clinic1
2,2,10/6/2010,_,0.000928,4.298943,0.000041,Clinic1
3,3,10/21/2010,0.877617221,0.002254,9.240019,0.000182,Clinic1
4,4,11/26/2010,_,0.008547,6.659528,0.000022,Clinic1

In [39]:
# checking number of rows and columns in the dataframe

df2_clean.shape

(22, 7)

In [40]:
# checking data types for all columns in the dataframe

df2_clean.dtypes

Unnamed: 0           int64
Inspection Date     object
M1                  object
M2                 float64
M3                 float64
M4                 float64
Site Name           object
dtype: object

### **Issue 1: Removing unnecessary column ('Unnamed').**

In [41]:
# using the drop method to remove 'Unnamed' column
df2_clean = df2_clean.drop(columns=['Unnamed: 0'])

#displaying dataframe head to check 'Unnamed' column is removed
df2_clean.head()

  Inspection Date           M1        M2        M3        M4 Site Name
0        9/4/2010  0.079600881  0.007344  0.542921  0.000074   Clinic1
1       9/27/2010            _  0.000204  9.613118  0.000042   Clinic1
2       10/6/2010            _  0.000928  4.298943  0.000041   Clinic1
3      10/21/2010  0.877617221  0.002254  9.240019  0.000182   Clinic1
4      11/26/2010            _  0.008547  6.659528  0.000022   Clinic1

In [42]:
# checking the shape of the dataframe after removing 1 column

df2_clean.shape

(22, 6)

### **Issue 2: Changing the data type for "Inspection Date", "M1" and "Site Name" columns.**

In [43]:
# change data type for "Inspection Date" column to datetime
df2_clean['Inspection Date'] = pd.to_datetime(df2_clean['Inspection Date'])

# confirming "Inspection Date" column is now in datetime format
df2_clean.head()

  Inspection Date           M1        M2        M3        M4 Site Name
0      2010-09-04  0.079600881  0.007344  0.542921  0.000074   Clinic1
1      2010-09-27            _  0.000204  9.613118  0.000042   Clinic1
2      2010-10-06            _  0.000928  4.298943  0.000041   Clinic1
3      2010-10-21  0.877617221  0.002254  9.240019  0.000182   Clinic1
4      2010-11-26            _  0.008547  6.659528  0.000022   Clinic1

In [44]:
# change data type for 'M1' column to numeric data type(float64) instead of 'object'

df2_clean['M1'] = pd.to_numeric(df2_clean['M1'], errors='coerce')

In [45]:
# checking changed to data type for 'Examination Date' and 'M1' is effected

df2_clean.dtypes

Inspection Date    datetime64[ns]
M1                        float64
M2                        float64
M3                        float64
M4                        float64
Site Name                  object
dtype: object

In [46]:
# checking for unique entries in 'Site Name' column

df2_clean['Site Name'].unique()

array(['Clinic1', 'Clinic2'], dtype=object)

In [47]:
# using sitename_type to set the 'Site Name' column as categorical data

sitename_type = pd.CategoricalDtype(categories=['Clinic1', 'Clinic2'])

df2_clean['Site Name'] = df2_clean["Site Name"].astype(sitename_type)

In [48]:
# checking that the object type for 'Site Name' is in category format

df2_clean.dtypes

Inspection Date    datetime64[ns]
M1                        float64
M2                        float64
M3                        float64
M4                        float64
Site Name                category
dtype: object

### **Issue 3: Checking for duplicates and removing them if there ia any.**

In [49]:
duplicate_rows2 = df2_clean.duplicated()

duplicate_rows2

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
dtype: bool

In [50]:
# counting the unique entries in duplicate rows

duplicate_rows2.nunique()

1

**"False" in duplicate_rows2 means that there are no duplicates. Since only False shows up, it means there are no duplicates in the dataframe.**